import { StyleSheet } from 'react-native';

export const PURPLE = '#7b3cff';
export const DARK_BG = '#0b021b';

export const styles = StyleSheet.create({
  // Generic full-page layout for forms/flows
  screenRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  screenBody: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  screenFooter: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  header: {
    height: 56,
    paddingHorizontal: 16,
    backgroundColor: DARK_BG,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBack: {
    padding: 8,
    marginRight: 8,
  },
  headerBackText: {
    color: '#ffffff',
    fontSize: 20,
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  stepTabsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 24,
    // paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    // borderTopWidth: 1,
    // borderTopColor: 'red',
  },
  stepTab: {
    alignItems: 'center',
    flex: 1,
  },
  stepTabText: {
    // fontSize: 16,
    color: '#6b7280',
    // fontWeight: '500',
    paddingVertical: 12,
  },
  stepTabTextActive: {
    color: PURPLE,
  },
  stepTabUnderline: {
    height: 2,
    width: '100%',
    marginTop: 4,
    borderRadius: 999,
    backgroundColor: 'transparent',
  },
  stepTabUnderlineActive: {
    backgroundColor: PURPLE,
  },
  splashContainer: {
    flex: 1,
    backgroundColor: DARK_BG,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashContent: {
    alignItems: 'center',
  },
  splashTitle: {
    marginTop: 24,
    fontSize: 32,
    fontWeight: '700',
    color: '#ffffff',
  },
  onboardingRoot: {
    flex: 1,
    backgroundColor: DARK_BG,
  },
  onboardingTop: {
    flex: 2,
  },
  onboardingBackgroundImage: {
    opacity: 0.3,
  },
  onboardingImageOverlay: {
    flex: 1,
    backgroundColor: 'rgba(11, 2, 27, 0.4)',
  },
  onboardingCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
    alignItems: 'center',
  },
  onboardingTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
  },
  onboardingDescription: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  pagination: {
    flexDirection: 'row',
    marginTop: 16,
    marginBottom: 24,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 4,
  },
  dotActive: {
    backgroundColor: PURPLE,
  },
  dotInactive: {
    backgroundColor: '#e5e7eb',
  },
  primaryButton: {
    marginTop: 'auto',
    width: '100%',
    backgroundColor: PURPLE,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryButtonBottom: {
    marginTop: 'auto',
    marginHorizontal: 16,
    marginBottom: 24,
    backgroundColor: PURPLE,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  languageRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  languageHeaderIcon: {
    // width: 40,
    // height: 40,
    borderRadius: 20,
    // backgroundColor: '#111827',
    marginBottom: 10,
  },
  languageTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  languageSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 16,
  },
  languageList: {
    flex: 1,
  },
  languageItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  languageItemSelected: {
    borderColor: PURPLE,
    backgroundColor: '#f5f3ff',
  },
  languagePrimary: {
    fontSize: 16,
    color: '#111827',
  },
  languagePrimarySelected: {
    fontWeight: '600',
  },
  languageSecondary: {
    fontSize: 14,
    color: '#6b7280',
  },
  // Mandal step toggles (Public/Private, Yes/No)
  mandalToggleRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  mandalToggle: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mandalToggleSelected: {
    borderColor: PURPLE,
    backgroundColor: '#f5f3ff',
  },
  mandalToggleText: {
    fontSize: 16,
    color: '#6b7280',
  },
  mandalToggleTextSelected: {
    color: PURPLE,
    fontWeight: '600',
  },
  permissionsRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  permissionsHeaderIcon: {
    width: 40,
    height: 40,
    // borderRadius: 20,
    // backgroundColor: '#111827',
    // marginBottom: 16,
  },
  permissionsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  permissionsSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 16,
  },
  permissionsList: {
    flex: 1,
  },
  permissionItem: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  permissionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    // backgroundColor: '#e5e7eb',
    marginRight: 12,
  },
  permissionTextContainer: {
    flex: 1,
  },
  permissionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 2,
  },
  permissionDescription: {
    fontSize: 14,
    color: '#6b7280',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.6)',
    justifyContent: 'flex-end',
  },
  fullscreenOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  allowAccessCard: {
    width: '85%',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    elevation: 4,
  },
  allowAccessIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#f5f3ff',
    alignSelf: 'center',
    marginBottom: 16,
  },
  allowAccessTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 16,
  },
  allowAccessOption: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  allowAccessOptionText: {
    fontSize: 14,
    color: '#111827',
    textAlign: 'center',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
  },
  modalIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#f5f3ff',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalText: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 24,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalSecondaryButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingVertical: 12,
    alignItems: 'center',
    marginRight: 8,
  },
  modalSecondaryText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6b7280',
  },
  modalPrimaryButton: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: PURPLE,
    paddingVertical: 12,
    alignItems: 'center',
    marginLeft: 8,
  },
  modalPrimaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  loginRoot: {
    flex: 1,
    backgroundColor: DARK_BG,
  },
  loginCardTop: {
    flex: 2,
  },
  loginTopContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginLogo: {
    width: 160,
    height: 160,
  },
  loginCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 100,
  },
  loginTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  loginSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  inputGroup: {
    marginTop: 8,
  },
  inputFloatingLabel: {
    position: 'absolute',
    left: 18,
    top: -10,
    paddingHorizontal: 4,
    backgroundColor: '#ffffff',
    fontSize: 12,
    color: '#6b7280',
    zIndex: 1,
  },
  inputFloatingLabelActive: {
    color: PURPLE,
  },
  inputFloatingLabelError: {
    color: '#ef4444',
  },
  inputWrapper: {
    borderWidth: 1,
    borderRadius: 12,
    borderColor: '#e5e7eb',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  inputWrapperError: {
    borderColor: '#f87171',
  },
  inputWrapperFocused: {
    borderColor: '#9ca3af',
  },
  inputWrapperSuccess: {
    borderColor: PURPLE,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
    // height: 36,
  },
  inputErrorIcon: {
    marginLeft: 8,
    color: '#ef4444',
    fontWeight: '700',
  },
  inputRightIcon: {
    marginLeft: 8,
    color: '#6b7280',
    // fontSize: 24,
  },
  inputErrorText: {
    marginTop: 4,
    fontSize: 13,
    color: '#ef4444',
  },
  inputHelperText: {
    marginTop: 4,
    fontSize: 13,
    color: '#ffffff00',
  },
  ctaButton: {
    marginTop: 'auto',
    marginBottom: 8,
    width: '100%',
    backgroundColor: PURPLE,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  ctaButtonDisabled: {
    backgroundColor: '#d1d5db',
  },
  ctaButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  otpFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  resendText: {
    fontSize: 14,
    color: PURPLE,
    fontWeight: '500',
  },
  attemptsText: {
    fontSize: 14,
    color: '#ef4444',
  },
  backToLogin: {
    marginTop: 16,
    alignItems: 'center',
  },
  backToLoginText: {
    fontSize: 14,
    color: PURPLE,
    fontWeight: '500',
  },
  selectionModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.6)',
    justifyContent: 'flex-end',
  },
  selectionModalCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
    maxHeight: '70%',
  },
  selectionModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 20,
  },
  selectionModalSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    backgroundColor: '#ffffff',
  },
  selectionModalSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
    paddingVertical: 12,
  },
  selectionModalSearchIcon: {
    // fontSize: 18,
    color: '#6b7280',
  },
  selectionModalSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginTop: 16,
    marginBottom: 12,
  },
  selectionModalList: {
    maxHeight: 400,
    marginBottom: 16,
  },
  selectionModalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    backgroundColor: '#ffffff',
  },
  selectionModalItemFirst: {
    marginTop: 0,
  },
  selectionModalItemLast: {
    marginBottom: 0,
  },
  selectionModalItemSelected: {
    backgroundColor: '#f5f3ff',
    borderColor: PURPLE,
  },
  selectionModalItemText: {
    fontSize: 16,
    color: '#111827',
    fontWeight: '500',
  },
  selectionModalItemTextSelected: {
    color: PURPLE,
    fontWeight: '600',
  },
  selectionModalCheckmark: {
    // fontSize: 18,
    color: PURPLE,
    fontWeight: '700',
  },
  selectionModalButton: {
    width: '100%',
    backgroundColor: PURPLE,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
  },
  selectionModalButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  filePickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.6)',
    justifyContent: 'flex-end',
  },
  filePickerCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
  },
  filePickerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  filePickerSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 24,
  },
  filePickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    backgroundColor: '#ffffff',
  },
  filePickerOptionIcon: {
    fontSize: 28,
    marginRight: 16,
  },
  filePickerOptionContent: {
    flex: 1,
  },
  filePickerOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  filePickerOptionSubtitle: {
    fontSize: 14,
    color: '#6b7280',
  },
  filePickerCancel: {
    marginTop: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  filePickerCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6b7280',
  },
  mapContainer: {
    marginTop: 8,
    position: 'relative',
    borderRadius: 16,
    overflow: 'hidden',
  },
  mapPlaceholder: {
    height: 200,
    backgroundColor: '#1f2937',
    borderRadius: 16,
    position: 'relative',
    overflow: 'hidden',
  },
  mapRoad1: {
    position: 'absolute',
    top: '30%',
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#374151',
    opacity: 0.6,
  },
  mapRoad2: {
    position: 'absolute',
    top: '60%',
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#374151',
    opacity: 0.6,
  },
  mapRoad3: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '40%',
    width: 3,
    backgroundColor: '#374151',
    opacity: 0.6,
  },
  mapMarker: {
    position: 'absolute',
    top: '35%',
    left: '35%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    zIndex: 10,
  },
  mapMarkerPin: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ef4444',
    borderWidth: 3,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 8,
  },
  editLocationButton: {
    position: 'absolute',
    bottom: 16,
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  editLocationButtonText: {
    color: PURPLE,
    fontSize: 14,
    fontWeight: '600',
  },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F6F2FC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    // marginTop: 12,
  },
  locationIcon: {
    fontSize: 18,
    marginRight: 12,
    marginTop: 2,
  },
  locationText: {
    flex: 1,
    fontSize: 14,
    color: '#111827',
    lineHeight: 20,
  },

  // Mandal Step 3 - Add Member
  memberAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  memberAddFab: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
    marginRight: 12,
  },
  memberAddFabIcon: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
  },
  memberAddText: {
    fontSize: 16,
    color: PURPLE,
    fontWeight: '600',
  },

  // Invite Members modal
  inviteSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: '#ffffff',
  },
  inviteSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
    paddingVertical: 10,
  },
  inviteSearchIcon: {
    fontSize: 18,
    color: '#6b7280',
  },
  inviteSelectedWrapper: {
    marginBottom: 12,
  },
  inviteSelectedCount: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 8,
  },
  inviteSelectedScroll: {
    paddingVertical: 4,
  },
  inviteSelectedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
  },
  inviteSelectedAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e5deff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  inviteSelectedAvatarText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4b0082',
  },
  inviteSelectedName: {
    maxWidth: 80,
    fontSize: 13,
    color: '#111827',
  },
  inviteSelectedRemove: {
    marginLeft: 4,
  },
  inviteSelectedRemoveText: {
    fontSize: 14,
    color: '#6b7280',
  },
  inviteAllContactsLabel: {
    fontSize: 13,
    color: '#6b7280',
    marginTop: 8,
    marginBottom: 8,
  },
  inviteContactsList: {
    marginTop: 4,
  },
  inviteContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 8,
    backgroundColor: '#ffffff',
  },
  inviteContactRowSelected: {
    backgroundColor: '#f5f3ff',
    borderColor: PURPLE,
  },
  inviteContactAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e5deff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  inviteContactAvatarText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4b0082',
  },
  inviteContactInfo: {
    flex: 1,
  },
  inviteContactName: {
    fontSize: 15,
    color: '#111827',
  },
  inviteContactNumber: {
    fontSize: 13,
    color: '#6b7280',
  },
  inviteContactCheck: {
    fontSize: 18,
    color: PURPLE,
    marginLeft: 8,
  },
  inviteFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  inviteFooterButton: {
    width: '100%',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: PURPLE,
  },
  inviteFooterButtonDisabled: {
    backgroundColor: '#d1d5db',
  },
  inviteFooterButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
});


