import { StyleSheet } from 'react-native';

const PURPLE = '#7E48DC';

export const homeStyles = StyleSheet.create({
  // Homepage root
  homeRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  // Header styles
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  homeHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeLogo: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    overflow: 'hidden',
  },
  homeLogoImage: {
    width: '100%',
    height: '100%',
  },
  homeLogoText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  homeHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeHeaderIcon: {
    // padding: 5,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Content area
  homeContent: {
    flex: 1,
  },
  // Mandal Profiles Section
  mandalProfilesSection: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingHorizontal: 16,
  },
  // mandalProfilesList: {
  //   paddingHorizontal: 16,
  // },
  mandalProfileCard: {
    alignItems: 'center',
    marginRight: 16,
    width: 80,
  },
  mandalProfileImageContainer: {
    width: 70,
    height: 70,
    marginBottom: 8,
    position: 'relative',
  },
  mandalProfileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#dc2626',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  mandalProfileImageWithMembers: {
    borderWidth: 3,
    borderColor: '#7E48DC', // Dark border when members exist
  },
  mandalProfileImageWithoutMembers: {
    borderWidth: 3,
    borderColor: '#D1BDF2', // Light border when no members
  },
  mandalProfileEmoji: {
    fontSize: 32,
  },
  mandalProfileImageContent: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  mandalProfileBadge: {
    position: 'absolute',
    bottom: -10,
    // right: 0,
    // top: -10,
    left: 24,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#7E48DC',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  mandalProfileBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
  },
  mandalProfileName: {
    fontSize: 12,
    color: '#111827',
    textAlign: 'center',
    maxWidth: 80,
    marginTop: 4,
  },
  // Posts Feed
  postsFeed: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  postCard: {
    backgroundColor: '#ffffff',
    marginBottom: 16,
    paddingBottom: 16,
    // paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  postHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    // paddingHorizontal: 16
  },
  postHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  postAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#dc2626',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  postAvatarEmoji: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#dc2626',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D1BDF2',
    // marginRight: 12,
  },
  postMandalName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  postTime: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  joinButton: {
    // backgroundColor: PURPLE,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D1BDF2',
  },
  joinButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: "#7E48DC",
  },
  postText: {
    fontSize: 14,
    color: '#111827',
    lineHeight: 20,
    marginBottom: 12,
    // paddingHorizontal: 16
  },
  postUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    // paddingHorizontal: 16
  },
  postUserName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginRight: 8,
  },
  topVoiceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: '#fef3c7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  topVoiceIcon: {
    fontSize: 12,
    marginRight: 4,
  },
  topVoiceText: {
    fontSize: 12,
    // fontWeight: '600',
    color: '#000',
  },
  // Event styles
  eventTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#E3D8F7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 12,
    marginTop: 10,
    // marginHorizontal: 16
  },
  eventTagText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7E48DC',
  },
  postMedia: {
    marginBottom: 2,
    overflow: 'hidden',
  },
  postImagePlaceholder: {
    width: '100%',
    height: 200,
    backgroundColor: '#e5e7eb',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  postImage: {
    width: '100%',
    height: '100%',
  },
  postImagePlaceholderText: {
    fontSize: 14,
    color: '#6b7280',
  },
  speakerIcon: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  eventMediaContainer: {
    flexDirection: 'row',
    height: 200,
  },
  eventMediaLeft: {
    flex: 1,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  eventMediaImage: {
    width: '100%',
    height: '100%',
  },
  eventMediaRight: {
    flex: 1,
    backgroundColor: '#dc2626',
    padding: 16,
    justifyContent: 'space-between',
  },
  eventMediaLogo: {
    fontSize: 10,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'right',
  },
  eventMediaTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 20,
  },
  eventMediaBar: {
    backgroundColor: '#f97316',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    marginTop: 20,
  },
  eventMediaBarText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
  },
  joinEventButton: {
    backgroundColor: PURPLE,
    paddingVertical: 12,
    paddingHorizontal: 20,
    // borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
    // marginHorizontal: 16
  },
  joinEventButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  discoverContainer: {
    paddingHorizontal: 16,
  },
  // Discover page
  discoverSearchContainer: {
    // paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: '#ffffff',
  },
  discoverSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  discoverSearchInput: {
    flex: 1,
    marginHorizontal: 8,
    fontSize: 14,
    color: '#111827',
  },
  discoverFiltersRow: {
    flexDirection: 'row',
    marginTop: 12,
    alignItems: 'center',
  },
  discoverFilterTuneButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginRight: 8,
  },
  discoverFilterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
    marginRight: 8,
  },
  discoverFilterChipActive: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#111827',
    marginRight: 8,
  },
  discoverFilterText: {
    fontSize: 12,
    color: '#6b7280',
  },
  discoverFilterTextActive: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  // Search Results
  searchResultsSection: {
    paddingVertical: 16,
    // borderBottomWidth: 1,
    // borderBottomColor: '#e5e7eb',
  },
  searchResultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    // paddingHorizontal: 16,
  },
  searchResultsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  showAllButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
  },
  showAllButtonText: {
    fontSize: 12,
    color: '#6b7280',
  },
  mandalResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    // paddingHorizontal: 16,
    // borderBottomWidth: 1,
    // borderBottomColor: '#e5e7eb',
  },
  mandalResultAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
    overflow: 'hidden',
    backgroundColor: '#f3f4f6',
  },
  mandalResultAvatarImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  mandalResultAvatarPlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#e5e7eb',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mandalResultAvatarText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#6b7280',
  },
  mandalResultInfo: {
    flex: 1,
  },
  mandalResultName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  mandalResultLocation: {
    fontSize: 12,
    color: '#6b7280',
  },
  loadingMoreText: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  loadingMoreTextContent: {
    fontSize: 12,
    color: '#6b7280',
    marginLeft: 8,
  },
  // Advanced Filters
  advancedFiltersContainer: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  advancedFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  advancedFilterChipActive: {
    backgroundColor: PURPLE,
    borderColor: PURPLE,
  },
  advancedFilterText: {
    fontSize: 12,
    color: '#6b7280',
    marginRight: 4,
  },
  advancedFilterTextActive: {
    color: '#ffffff',
    fontWeight: '600',
  },
  discoverAnnouncement: {
    // paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
  },
  discoverAnnouncementTitle: {
    fontSize: 12,
    color: '#111827',
    marginBottom: 4,
  },
  discoverFeaturedCard: {
    // paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: '#ffffff',
  },
  discoverFeaturedImageWrapper: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  discoverFeaturedImage: {
    width: '100%',
    height: 220,
  },
  discoverFeaturedOverlay: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
  },
  discoverFeaturedYear: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
  },
  discoverFeaturedTitle: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 1,
  },
  discoverFeedSection: {
    backgroundColor: '#ffffff',
    // paddingHorizontal: 16,
    paddingBottom: 24,
  },
  discoverListItem: {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  discoverListText: {
    flex: 1,
    paddingRight: 12,
  },
  discoverListTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  discoverListDescription: {
    fontSize: 12,
    color: '#6b7280',
    lineHeight: 18,
  },
  discoverListImageWrapper: {
    width: 100,
    height: 90,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  discoverListImage: {
    width: '100%',
    height: '100%',
  },
  discoverListPlayIcon: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -16,
    marginLeft: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Post actions
  postActionsOuter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    // paddingHorizontal: 10
  },
  postActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    // paddingHorizontal: 16
  },
  postAction: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 5,
    marginLeft: 5,
  },
  postActionSpacer: {
    flex: 1,
  },
  postActionIcon: {
    fontSize: 20,
    marginRight: 4,
  },
  postActionCount: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
  },
  // Bottom Navigation
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 8,
    paddingBottom: 16,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  bottomNavItem: {
    alignItems: 'center',
    flex: 1,
  },
  bottomNavIcon: {
    marginBottom: 4,
  },
  bottomNavLabel: {
    fontSize: 12,
    color: '#6b7280',
  },
  bottomNavLabelActive: {
    color: PURPLE,
    fontWeight: '600',
  },
  // Search Filters Modal
  searchFiltersModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  searchFiltersModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  searchFiltersModalContent: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 24,
    paddingHorizontal: 16,
    maxHeight: '85%',
  },
  searchFiltersModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 24,
  },
  searchFiltersScrollView: {
    flex: 1,
  },
  searchFiltersSection: {
    marginBottom: 32,
  },
  searchFiltersSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 16,
  },
  searchFiltersLocationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  searchFiltersLocationInput: {
    flex: 1,
    fontSize: 14,
    color: '#111827',
  },
  currentLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3D8F7',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
  },
  currentLocationButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: PURPLE,
    marginLeft: 8,
  },
  selectedLocationsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  selectedLocationTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 6,
  },
  selectedLocationTagText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  locationSuggestionsContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
  },
  locationSuggestionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  locationSuggestionText: {
    fontSize: 14,
    color: '#111827',
  },
  searchFilterOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  searchFilterOptionText: {
    fontSize: 14,
    color: '#111827',
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#6b7280',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: PURPLE,
  },
  searchFiltersModalActions: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingTop: 24,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  searchFiltersCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  searchFiltersCancelButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
  },
  searchFiltersApplyButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: PURPLE,
    alignItems: 'center',
  },
  searchFiltersApplyButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
});

