import { StyleSheet } from 'react-native';

const PURPLE = '#7E48DC';

export const profileStyles = StyleSheet.create({
  profileSection: {
    padding: 16,
    // borderBottomWidth: 1,
    // borderBottomColor: '#e5e7eb',
    backgroundColor: "#110723",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingBottom: 30,
  },
  postsFeedsection: {
    // paddingHorizontal: 16,
  },
  profileHeader: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginRight: 16,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  profileLocation: {
    fontSize: 14,
    color: '#808F9E',
    marginBottom: 4,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 4,
  },
  verifiedText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#808F9E',
    marginRight: 4,
  },
  profileOccupation: {
    fontSize: 14,
    color: '#808F9E',
    marginTop: 4,
    marginBottom: 4,
  },
  profileBio: {
    fontSize: 14,
    color: '#fff',
    lineHeight: 20,
    marginBottom: 16,
  },
  profileButtonsRow: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 8,
  },
  profileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#331469',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  profileButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF8A5F',
  },
  influencialButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0093E1',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 16,
    borderTopColor: '#e5e7eb',
    borderBottomColor: '#e5e7eb',
    marginBottom: 16,
  },
  statItem: {
    alignItems: 'left',
  },
  statNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#fff',
  },
  profileActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flex: 1,
    backgroundColor: "#331469",
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: 'center',
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7E48DC',
  },
  section: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // paddingHorizontal: 16,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  sectionLink: {
    fontSize: 14,
    color: PURPLE,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionLinkText: {
    fontSize: 14,
    color: '#F13030',
  },
  mandalsList: {
    paddingVertical: 8,
  },
  recommendedMandalCard: {
    flexDirection: 'row',
    alignItems: 'center',
    // paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  recommendedMandalAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
  },
  recommendedMandalInfo: {
    flex: 1,
  },
  recommendedMandalName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  recommendedMandalDetails: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 2,
  },
  recommendedMandalLocation: {
    fontSize: 12,
    color: '#6b7280',
  },
  joinMandalButton: {
    // backgroundColor: PURPLE,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D1BDF2',
  },
  joinMandalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: "#7E48DC",
  },
  exploreCard: {
    backgroundColor: '#110723',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 160,
  },
  exploreCardContent: {
    flex: 1,
    marginRight: 16,
  },
  exploreCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 8,
  },
  exploreCardDescription: {
    fontSize: 14,
    color: '#808F9E',
    marginBottom: 16,
    lineHeight: 20,
  },
  exploreNowButton: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: PURPLE,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  exploreNowButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: PURPLE,
  },
  exploreCardGraphic: {
    width: 130,
    height: 130,
    justifyContent: 'flex-start',
    alignItems: 'center',
    // paddingTop: 10,
  },
  exploreCardGraphicImage: {
    width: 130,
    height: 130,
    resizeMode: 'contain',
  },
  emptyPostCard: {
    borderWidth: 1,
    borderStyle: 'dotted',
    borderColor: '#D1BDF2',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
  },
  emptyPostIconsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    marginBottom: 12,
  },
  emptyPostIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyPostText: {
    fontSize: 14,
    color: '#7E48DC',
    fontWeight: '500',
  },
});

